### ISSUE TITLE
UC-1: Visualize Algorithm

### ISSUE THREAD

**Issue by uptonm** [path2finding/visualizer#18]
Adds the ability to visualize a pathfinding algorithm finding the shortest path between two points.

- [x]  #14 - Set Visualization Speed
- [X]  #12 - Stop Visualization
- [X]  #13 - Start/Resume Visualization

In addition to the above tasks, we should be able to simulate the runtime of the following algorithms:

- [x] #65 - A*
- [x] #66 - Djikstras
- [x] #67 - BFS - Breadth-first Search
- [x] #68 - DFS - Depth-first Search
